# Generated by Django 5.0.1 on 2025-02-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outh", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.FileField(blank=True, null=True, upload_to="profile"),
        ),
    ]
